export const GET_CURRENT_USERS_ON_MAP = 'GET_CURRENT_USERS_ON_MAP';
export const SET_MAP_STAGE = 'SET_MAP_STAGE';
export const SET_MAP_PAGE_ACCESS = 'SET_MAP_PAGE_ACCESS';
export const SET_MY_LOCATION = 'SET_MY_LOCATION';
