export const GET_ALL_NEWS = 'GET_ALL_NEWS';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_ERROR = 'GET_ALL_NEWS_ERROR';

export const UPDATE_LIKES_COUNTER = 'UPDATE_LIKES_COUNTER';
export const UPDATE_LIKES_COUNTER_SUCCESS = 'UPDATE_LIKES_COUNTER_SUCCESS';
export const UPDATE_LIKES_COUNTER_ERROR = 'UPDATE_LIKES_COUNTER_ERROR';
