export const GET_RANDOM_BAR = 'GET_RANDOM_BAR';
export const SET_BAR_EFFORT = 'SET_BAR_EFFORT';

export const ADD_TO_ALL_RANDOM_BARS = 'ADD_TO_ALL_RANDOM_BARS';
export const INIT_ALL_RANDOM_BARS = 'INIT_ALL_RANDOM_BARS';
