export const GET_RANDOM_BAR = 'GET_RANDOM_BAR';
export const SET_BAR_EFFORT = 'SET_BAR_EFFORT';
export const GET_BAR_EFFORT_COOKIE = 'GET_BAR_EFFORT_COOKIE';
export const SET_BAR_EFFORT_COOKIE = 'SET_BAR_EFFORT_COOKIE';
